name: CD

on:
  workflow_dispatch:
    inputs:
      image: 
        required: true
        description: 'Enter image repository'
        default: ''
      tag: 
        required: true
        description: 'Enter image tag'
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4

    - name: Login to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2     

    - name: Set project
      run: gcloud config set project actions-333

    - name: Install gcloud auth plugin  
      run: gcloud components install gke-gcloud-auth-plugin

    - name: Generate kube config file
      run: gcloud container clusters get-credentials cluster-1 --region us-central1 --project actions-333

    - name: Install app
      run: |
        helm upgrade --install flask ./flask \
        --set deployment.image.repository=${{ github.event.inputs.image }} \
        --set deployment.image.tag=${{ github.event.inputs.tag }}